package org.apache.dolphinscheduler.common.utils;

import org.apache.dolphinscheduler.common.Constants;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;

/**
 *  CustomVariableValue
 */
public class NewLandCustomVariableValueUtils {
    private static final Logger logger = LoggerFactory.getLogger(NewLandCustomVariableValueUtils.class);

    public Map<String,String> getVariableValues(){
        Map<String,String> resMap = new HashMap<>();
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");
        resMap.put(Constants.PRE_MON_YEAR_NUMBER,"");

        return resMap;
    }
}
